Small display support
jubalh/nudoku pull request #23
Opened 2018-10-31 21:38 UTC by jeroanan

Hi,

I have made some changes to make Nudoku playable on the 3.5" display I have attached to my Raspberry Pi.

The changes can be activated by defining SMALL_DISPLAY. I have been doing this by passing CPPFLAGS into configure.

Commit 2e5180b removes empty space from around the screen, making the game board and info box to the right _just_ fit onto the 3.5" display.

Commit cb3ed2b makes the very top line of the screen display the status message if there is one, or else it's the top border of the game board. Once a message is displays it is dismissed and replaced by the top border of the game board on the next keystroke.

Commit 28aa38a is a small change to the docs as I found I had to install gettext when compiling on Raspbian, so I've added it as a dependency.

Yours sincerely,
Dave Wilson (Jeroanan).

2018-11-01 19:41 UTC, jubalh commented
Hi Dave,
Thanks for the patch. Will try to review it soon.
Thanks already for the gettext, it's true that this is needed with the git version but not latest stable release.

Could you also attach a picture of what it looks like here if it wouldn't be too much trouble for you?

2018-11-02 22:03 UTC, jeroanan commented
Hi,

Sorry for the slight delay -- here are a couple of screen shots. In both of them I have how it looks when built without my change on the left and on the right is when built with the new preprocessor variable defined. Note that in the second screen shot, "Provided hint" will be replaced with the top border of the game board the next time the user presses a key.
![screenshot-1](https://user-images.githubusercontent.com/4148242/47942768-0fe2c200-deeb-11e8-9524-f4b5d85bff7b.jpg)
![screenshot-2](https://user-images.githubusercontent.com/4148242/47942770-107b5880-deeb-11e8-8aed-8815c29d8b74.jpg)

2018-11-03 10:06 UTC, jubalh requested changes

2018-11-03 10:06 UTC, jubalh commented on src/main.c
> +#ifndef SMALL_DISPLAY
please create one block #ifdef SMAPP_DISPLAY and do all the things in there, and one #else block where you do the rest. for the defines.

2018-11-03 10:06 UTC, jubalh commented on src/main.c
> +void erase_status(void) {
i dont see a need for such a function.

2018-11-03 10:06 UTC, jubalh commented on src/main.c
> +				}
one space after the }

2018-11-03 10:06 UTC, jubalh commented on src/main.c
> +#ifdef SMALL_DISPLAY
wont it fit another way?

2023-12-20 18:59 UTC, jubalh commented
No answer

2023-12-20 18:59 UTC, closed without merging