Allow pausing
jubalh/nudoku pull request #48
Opened 2022-06-30 15:16 UTC by dogukanteber

Resolves #47. Now the users can save the game and quit. If the game is saved, the next time they open nudoku, a pop-up asks them to resume where they left off or create a new game. Currently, there is no coloring in the pop-up. If there is a necessity to add colors, it is not a difficult task. It can be added easily as long as which colors is going to be used are provided.

2022-06-30 15:51 UTC, jubalh commented
Thanks! I'll try to review it soon!

2022-08-24 13:53 UTC, jubalh requested changes
The code looks good! Thank you!
I made some comments about where I think there need to be changes.
Sorry for the long delay! :(

2022-08-24 13:53 UTC, jubalh commented on src/main.c
> +static bool is_board_solved = false;		/* if the board is solved, we do not save the state */
I would propose to remove this variable and not check if the user solved/not ask him if he wants to save.
I would like to just have an option "lets save". And the user can do this when he wants but don't add the overhead of tracking this and asking him.

2022-08-24 13:53 UTC, jubalh commented on src/main.c
> +	wprintw(infobox, _(" G - Save and quit\n"));
I think `save` is enough. The user can use `save` and then `quit`.

2022-08-24 13:53 UTC, jubalh commented on src/main.c
> +	const char* dir_name = "/.nudoku/";
I think we should use something like: https://specifications.freedesktop.org/basedir-spec/basedir-spec-latest.html
Most likely: ` $XDG_STATE_HOME defines the base directory relative to which user-specific state files should be stored. If $XDG_STATE_HOME is either not set or empty, a default equal to $HOME/.local/state should be used. `

2022-08-24 13:53 UTC, jubalh commented on src/main.c
> +	return file_path;
When is this file removed again? I think in `is_game_saved` you test for the presence of it. But I don't see where it get's removed when the game is finished.

2023-12-20 19:20 UTC, jubalh commented
@dogukanteber ping

2023-12-25 13:43 UTC, dogukanteber commented
Wow! It has been quite some time. I completely forgot about this PR @jubalh. My apologies. I will try to allocate some time to finish up this PR.

2024-08-06 19:45 UTC, merv1n34k commented
@dogukanteber @jubalh Do you mind if I try to finish up this PR? *(will create a new one though)*
I have more free time than usual for a few days, and with the help of @dogukanteber's code it looks doable for me.

2024-08-07 05:48 UTC, jubalh commented
Sure! Go for it :)

2024-08-22 09:55 UTC, closed without merging