Fix for ambiguous games generation
jubalh/nudoku pull request #63
Opened 2024-08-06 12:25 UTC by merv1n34k

This should fix #50. 
Solved few puzzles on hard level, haven't found any issues.

2024-08-06 14:24 UTC, jubalh requested changes
Thanks for this PR! :)
Please remove the 2nd commit though.

2024-08-06 14:55 UTC, merv1n34k commented
You're welcome :) 
Removed the 2nd.

2024-08-07 06:11 UTC, jubalh approved these changes

2024-08-07 06:12 UTC, merged

2024-08-07 06:12 UTC, jubalh commented
Thanks!