Highlight the currently selected character
jubalh/nudoku pull request #9
Opened 2018-04-04 18:50 UTC by FamousJameous

I thought it would be useful to highlight all occurrences of the number under the cursor as is done in many Sudoku apps. This makes it easier to find all occurrences of a certain number.

I am not a C or Curses expert so this commit is more of a suggestion for a more experienced developer to implement.

2018-04-05 07:58 UTC, jubalh commented
Thanks for your contribution!

I have a couple of suggestions:
* let's use a different color for the highlighted characters vs the current cursor position (orange?)
* let's make this feature optional, pressing `M` (for marks) to enable it first

Would you be willing to implement it this way?

This feature is related to https://github.com/jubalh/nudoku/issues/7

2018-04-05 15:08 UTC, FamousJameous commented
Thanks for the suggestions.

I definitely think making the feature optional is a good idea.

For the color, I want to make sure I understand. You want to have two highlight colors: one for the current cursor position (with white background and black foreground) and one for the other occurrences of the same number (with white background and orange foreground). I see that orange is not one of the eight basic colors, is 256 color support common enough to use it?

2018-04-05 15:40 UTC, FamousJameous commented
I tried several color combinations and I liked magenta background with black foreground the best. It is visibly obvious without being distracting. What do you think?

2018-04-05 15:46 UTC, jubalh commented
Looks good! Thanks for the changes!
I will look at the code tomorrow for more details :)

2018-04-05 15:51 UTC, jubalh commented
Please try to change the git commit message.
See [here](https://gist.github.com/robertpainsi/b632364184e70900af4ab688decf6f53)

Meaning no `.` in the first line. No more than 72 chars in the first line.

2018-04-05 15:51 UTC, jubalh requested changes

2018-04-05 15:51 UTC, jubalh commented on src/main.c
> +				// redraw grid to update highight
small typo here `highight`

2018-04-05 16:54 UTC, FamousJameous commented
I've never pushed rebased commits to Github before. It looks like it worked, but let me know if I messed something up.

2018-04-05 21:56 UTC, FamousJameous commented
Whoops, sorry. I guess I forgot to build after all that rebase stuff. Should be fixed now.

2018-04-05 22:02 UTC, jubalh commented
Very good job, thanks for your work.
I will add your name to the `AUTHORS` file, I will use the same format as for the others, if you don't want your email or real name or anything to be seen there just let me know.

2018-04-05 22:03 UTC, merged

2018-04-05 22:40 UTC, FamousJameous commented
I am trying to switch to a different email address than my Github default so use this if it works for you.
James 'FamousJameous' Warnock: James.Warnock.all@gmail.com

Thanks

2018-04-06 07:53 UTC, jubalh commented
Done.